### ISSUE TITLE
where is the bbb-conf utility in the docker image?

### ISSUE THREAD

**Issue by mario-evangelista-silva** [bigbluebutton/docker#89] opened 2021-04-21 16:13 UTC
where do I find the "bbb-conf" utility in the docker image to generate the BIGBLUEBUTTON_ENDPOINT and BIGBLUEBUTTON_SECRET credentials?

**Comment by dsjiern** [comment] 2021-04-25 10:16
You can set the SECRET in the .env-file:
![grafik](https://user-images.githubusercontent.com/29799323/115989636-99a50f00-a5bf-11eb-9a6f-de954b3e93c9.png)

Endpoint-URL is https://<YOURDOMAIN>/bigbluebutton/

**Comment by alangecker** [comment] 2021-04-25 12:00
basically a duplicate of #84

**Closed by alangecker** 2021-04-25 12:00 UTC

**Comment by ZelphirKaltstahl** [comment] 2022-01-09 17:21
> You can set the SECRET in the .env-file: ![grafik](https://user-images.githubusercontent.com/29799323/115989636-99a50f00-a5bf-11eb-9a6f-de954b3e93c9.png)
> 
> Endpoint-URL is https:///bigbluebutton/

Surely you mean, that there is some domain between `https://` and `/bigbluebutton/`?
